# Generated by Django 4.2 on 2024-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_follow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed_user")},
        ),
    ]
